---
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
  when: hardening_firewall_enable | bool

- name: Allow SSH Port in UFW
  community.general.ufw:
    rule: allow
    port: "{{ hardening_ssh_port | string }}"
    proto: tcp
  when: hardening_firewall_enable | bool

- name: Set default deny incoming policy
  community.general.ufw:
    direction: incoming
    policy: deny
  when: hardening_firewall_enable | bool

- name: Set default allow outgoing policy
  community.general.ufw:
    direction: outgoing
    policy: allow
  when: hardening_firewall_enable | bool

- name: Enable UFW
  community.general.ufw:
    state: enabled
  when: hardening_firewall_enable | bool
