---
- name: User Management
  ansible.builtin.include_tasks: users.yml

- name: System Updates
  ansible.builtin.include_tasks: updates.yml

- name: Configure SSH Hardening
  ansible.builtin.include_tasks: ssh.yml

- name: Configure Firewall
  ansible.builtin.include_tasks: firewall.yml

- name: Configure Unattended Upgrades
  ansible.builtin.include_tasks: unattended_upgrades.yml

- name: Configure Fail2Ban
  ansible.builtin.include_tasks: fail2ban.yml

- name: Configure Postfix MTA
  ansible.builtin.include_tasks: postfix.yml
